# Generated by Django 4.1.7 on 2023-03-08 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='crop',
            name='remark',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
