# Generated by Django 4.1.7 on 2023-03-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_desc_crop_description_crop_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='remark',
        ),
    ]
