# Generated by Django 4.1.7 on 2023-03-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pesticide_alter_crop_desc_alter_crop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Insecticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
