# Generated by Django 4.1.7 on 2023-03-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_fertilizer_insecticide_alter_crop_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('pesticide', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='InsecticideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('insecticide', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('fertilizer', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('npk', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crop')),
            ],
        ),
    ]
